disabled = false
locale = "it"
label = "Italiano"
weight = 1
title = "Francesco Maria Papulino"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Francesco Maria Papulino"
   email = "francescom.papulino@gmail.com"
   image = "foto_profilo1.jpeg"
   imageQuality = 96
   headline = "Security Senior Analyst @ Accenture"
   bio = "28 anni, Napoli."
   links = [
     { email = "mailto:francescom.papulino@gmail.com" },
     { github = "https://github.com/francescopapu" },
     { linkedin = "https://linkedin.com/in/francescomariapapulino" },
     { mastodon = "https://livellosegreto.it/@francescopapu" },
   ]
