# .github/workflows/gh-pages.yml

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          working-directory: ./website/

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.10.9
        with:
          working-directory: ./website/

      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
        with:
          working-directory: ./website/

      - run: tinacms build -c "hugo"
        working-directory: ./website/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          working-directory: ./website/
